apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapi
  namespace: carefirst
  labels: 
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pythonapi
        image: pythonapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
      - name: busybox
        image: busybox:latest
        command:
          - /bin/sh
          - -c
          - sleep 1000
      initContainers:
      - name: verify-redis-dns
        image: busybox:latest
        command: ['sh', '-c', "until nc -vz service-redis 6379; do echo 'waiting for redis service from DNS'; sleep 2; done"]
      - name: verify-redis-ready
        image: busybox:latest
        command:  ["sh", "-c", "until (printf 'PING\r\n';) | nc service-redis 6379; do echo 'waiting for redis to PONG'; sleep 1; done"]
