apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: carefirst
  labels: 
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontendcontainer
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000