apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: carefirst
  labels: 
    app: UI
spec:
  replicas: 3
  selector:
    matchLabels:
      app: UI
  template:
    metadata:
      labels:
        app: UI
    spec:
      containers:
      - name: apicontainer
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000