---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: conversational
          image: local:latest
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
