---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carefirst
resources:
  - ../../base
  - virtual-service.yaml
patches:
  - path: patch-deployment-pythonapi.yaml
    target:
      kind: Deployment
      labelSelector: "app=api"
