---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: pythonapi
spec:
  hosts:
    - carefirst.mids255.com
  gateways:
    - istio-ingress/carefirst-gateway
  http:
    - match:
        - uri:
            exact: /conversations
        - uri:
            exact: /messages
        - uri:
            prefix: /health
        - uri:
            prefix: /docs
        - uri:
            prefix: /openapi.json
        - uri:
            prefix: /hello
      route:
        - destination:
            host: pythonapi
            port:
              number: 8000
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: pythonapi
            port:
              number: 3000
