---
apiVersion: v1
kind: Service
metadata:
  name: conversational
  labels:
    app: conversational
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: conversational
